import React from 'react';

const TermsAndConditions = () => {
  return (
    <div className="terms-and-conditions">
      <h1>DREAMSPORT Terms and Conditions</h1>
      <section>
        <h2>Introduction</h2>
        <p>
          This document is published in accordance with the provisions of Rule 3(1) of the Information Technology (Intermediaries Guidelines and Digital Media Ethics Code) Rules, 2021 that require publishing the rules and regulations, privacy policy and user agreement for access or usage of our website ‘www.dreamsport.shop’ (hereinafter referred to as the “Website”, “Mobile Application”, or “Platform”). DREAMSPORT Fantasy Sports Private Limited is incorporated under the Companies Act, 2013 having its registered office at Accelerator Coworking Space, Ground Floor, MGF Metropolis Mall, Mehrauli-Gurgaon Rd, Gurugram, Haryana 122002 (hereinafter, referred to as “we”, “us”, “our” and “DREAMSPORT”).
        </p>
        <p>
          This document is an electronic record in terms of the Information Technology Act, 2000 and rules made thereunder as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.
        </p>
        <p>
          For the purpose of these Terms and Conditions (defined hereinafter), “you”, “your” or “User” refers to any natural or legal person (whether a registered user or otherwise) who accesses the Website, its contents and uses the services offered by DREAMSPORT on or through the Website.
        </p>
      </section>

      <section>
        <h2>Acceptance of Terms</h2>
        <p>
          Your use of our Website and its related sites, services and tools is governed by these Terms and Conditions contained in this agreement that applies to the Website (“User Terms”). By using the Website, you have impliedly agreed to and accepted these User Terms. If you do not agree or are not willing to be bound by the terms and conditions of these User Terms (and the rules and policies displayed on the Website), please do not click on the REGISTER/LOGIN, SUBSCRIBE NOW or any other related buttons and do not seek to obtain access to or otherwise use the Website. As long as you comply with the provisions of these User Terms, we grant you a personal, non-exclusive, non-transferable, limited privilege to enter and use the Website.
        </p>
        <p>
          DREAMSPORT is not affiliated with any private or government sports leagues or tournaments unless explicitly stated. Additionally, DREAMSPORT does not have any official association with any sports teams or individuals.
        </p>
        <p>
          The term “DREAMSPORT” used in these Terms and Conditions, refers to both the DREAMSPORT Website and Mobile Application on Android Play Store and iOS App Store.
        </p>
      </section>

      <section>
        <h2>Intellectual Property</h2>
        <p>
          You may download or copy Content only to the extent such download is expressly permitted in writing on the Website. No right, title or interest in any downloaded materials or software is transferred to you as a result of any such downloading or copying. You may not reproduce (except as noted above), publish, transmit, distribute, display, modify, create derivative works from, sell or participate in any sale of or exploit in any way, in whole or in part, any of the Content, the Website or any related software.
        </p>
        <p>
          Nothing on the Website will be interpreted as granting any license or right to use any image, trademark, logo or service mark on the Website. Anything transmitted to the Website by you becomes DREAMSPORT property and may be used by us for any lawful purpose. DREAMSPORT reserves all rights with respect to copyright and trademark ownership of all material on the Website, and will enforce such rights to the full extent of the law.
        </p>
        <p>
          Unless otherwise noted, all Contents are copyrights, trademarks and/or other intellectual property owned, controlled or licensed by DREAMSPORT or by third parties who have licensed their materials to DREAMSPORT and are protected by Indian and international copyright laws. The compilation of all Contents on the Website is the exclusive property of DREAMSPORT and is also protected by Indian and international copyright laws.
        </p>
        <p>
          The Website, including all Information, is owned by or licensed to DREAMSPORT and is subject to and protected by various intellectual property rights, including but not limited to the copyright, trade secrets, trademarks, service marks, brand names and other proprietary rights whether under contract, statute or any similar provisions ( “IP Rights” ). All IP Rights are and will remain the exclusive property of DREAMSPORT, its respective third-party licensors or third parties to whom it is attributed and in using the Website, individual Users will not obtain any rights, title or other interest in or to any information on the Website or related IP Rights.
        </p>
        <p>
          Subject to the above, individual Users are entitled to view the Information on the Website and to copy and print such information for personal use. Individual Users are not permitted to sell or distribute or otherwise deal with the Information on the Website or any deviations of such information without the prior written consent of DREAMSPORT. The Website uses different web analytics services and is compliant with its Terms and Conditions.
        </p>
        <p>
          By accepting the T&Cs, the User grants DREAMSPORT and its affiliates, partners, licensors, and associates a worldwide, irrevocable, royalty-free, non-exclusive, sublicensable license to use, reproduce, create derivative works, distribute, publicly perform, publicly display, transfer, transmit and/or publish their User’s Content for the following purposes:
        </p>
        <ul>
          <li>Displaying User’s Content on DREAMSPORT;</li>
          <li>Distributing User’s Content to other users, electronically or through other media;</li>
          <li>Storing User’s Content in a remote database accessible by end users, for a charge; and</li>
          <li>This license applies to the distribution and storage of the User’s Content in any form, medium or technology.</li>
        </ul>
        <p>
          Permission to modify, publish, transmit, sell, reproduce, create derivative works or publicly display any content on www.dreamsport.shop can be requested at info@dreamsport.shop.
        </p>
        <p>
          The User is solely responsible for any material it uploads, posts, emails, transmits or makes available on DREAMSPORT ( “User’s Content” ). The User ensures that it holds the intellectual property rights in their User’s Content and that it does not infringe any third-party rights. User also agrees not to use or display any names, logos, marks, labels, trademarks, copyrights or intellectual property rights of any third party on DREAMSPORT. User accepts and agrees that DREAMSPORT and its directors, employees, affiliates, and assigns will not be liable for any costs, damages, loss or harm, including litigation costs and counsel fees, arising from any claims by a third party resulting from the display or use of any names, logos, marks, labels, trademarks, copyrights or intellectual property rights on DREAMSPORT through the User’s omissions.
        </p>
        <p>
          The User consents to receive communications, such as announcements, administrative messages and advertisements, from DREAMSPORT or any of its partners, licensors or associates.
        </p>
      </section>

      <section>
        <h2>Usage of Website and Mobile Application</h2>
        <p>
          Users using the services offered by www.dreamsport.shop or the DREAMSPORT App, including Features, by participating in various contests and games organized on the platform (“Contests”) are bound to follow these Terms and Conditions, and all other rules and regulations defined by DREAMSPORT.
        </p>
        <p>
         DREAMSPORT reserves the right to modify or change these Terms and Conditions, rules and regulations at any time by posting them on www.dreamsport.shop. By using DREAMSPORT services, Users agree to time-to-time amendments that may be made. Users will be informed of any amendments via email to their registered address or by posting notifications in their accounts. If a User disagrees or does not accept the amendments, they can indicate their non-acceptance within the defined time frame. If a user fails to do so, they will be deemed to have accepted the changes. In case of non-acceptance, DREAMSPORT reserves the right to restrict the User from using its services and features.
        </p>
        <p>
          Additional rules and regulations may apply to the various services offered as part of the features. If there are additional conditions that conflict with these Terms and Conditions, the additional conditions will take precedence.
        </p>
        <p>
          DREAMSPORT offers several interactive functionalities on the App to enhance the user experience. These functionalities are referred to as “features” in all the sections of these Terms and Conditions.
        </p>
        <p>
        DREAMSPORT may, at its discretion:
        </p>
        <ul>
          <li>Restrict, suspend or terminate a User’s access to all or part of www.dreamsport.shop or features of DREAMSPORT.</li>
          <li>Change, suspend or discontinue all or part of the features.</li>
          <li>Deactivate or delete a User’s account and related information and files.</li>
          <li>Reject, move or remove any material submitted by a User.</li>
          <li>Move or remove any content available on www.dreamsport.shop and DREAMSPORT application.</li>
          <li>Establish general practices and limits for the use of www.dreamsport.shop and DREAMSPORT application.</li>
          <li>Revise or add to the roster of players for selection in a Contest.</li>
          <li>Assign its rights and liabilities to another entity (after informing users via registered email).</li>
        </ul>
        <p>
          DREAMSPORT reserves the right to restrict, suspend, or terminate a user’s access, deactivate or delete their account and delete their content without notice if they breach these Terms and Conditions or use services or features illegally or inappropriately. DREAMSPORT may also take technical or legal action against such a user.
        </p>
        <p>
          In case of suspension or deletion due to DREAMSPORT negligence, DREAMSPORT will repay the platform fee charged for any features. No refund will be made in case of suspension or removal due to:
        </p>
        <ul>
          <li>Breach of these Terms and Conditions or inappropriate use of DREAMSPORT.</li>
          <li>Circumstances beyond DREAMSPORT reasonable control.</li>
        </ul>
        <p>
          By accepting these Terms and Conditions, Users agree to receive communications, including announcements, administrative messages and advertisements, from DREAMSPORT or its partners, licensors or associates.
        </p>
      </section>

      <section>
        <h2>Third-Party Sites, Services, and Products</h2>
        <p>
         DREAMSPORT platform may contain links to third-party sites, services and products that are owned and operated by independent entities. These third-party sites may have different terms of use for users. DREAMSPORT does not have control over or assume any responsibility for the content or practices of these third-party sites. The inclusion of links to third-party sites on DREAMSPORT does not imply endorsement of such sites or any affiliation with their operators.
        </p>
        <p>
          Users transact with third parties, including payment providers and verification service providers, at their own risk. Users are solely responsible for reviewing the policies, terms and conditions of these third parties before conducting any transactions or availing of any services. By accepting the Terms and Conditions of DREAMSPORT, users agree that DREAMSPORT is not responsible for any damages or losses incurred as a result of any transactions, correspondence or related activities with third parties. Any questions, complaints or claims regarding third-party products or services should be directed to the relevant vendor.
        </p>
        <p>
          www.dreamsport.shop and DREAMSPORT application features content created and posted by both DREAMSPORT and various third parties. DREAMSPORT does not guarantee the accuracy, integrity or quality of the content created by third parties and such content should not be relied upon by users in connection with the use of the features provided by DREAMSPORT or participation in any contests hosted on the platform.
        </p>
      </section>

      <section>
        <h2>Privacy Policy</h2>
        <p>
        DREAMSPORT collects user information, including personal details and payment information, at the time of registration. This information is subject to DREAMSPORT Privacy Policy, which can be reviewed by users on the Privacy Policy page.
        </p>
      </section>

      <section>
        <h2>User Conduct</h2>
        <p>
          The terms and conditions, rules, regulations and terms of use established by DREAMSPORT are binding on all users and must be strictly adhered to. If a user fails to comply with these terms, DREAMSPORT reserves the right to take action against the user, which may include but is not limited to:
        </p>
        <ul>
          <li>Restricting, suspending, or terminating a user’s access to all or any part of DREAMSPORT features;</li>
          <li>Deactivating or deleting a User’s account and all related information and files; or</li>
          <li>Refraining from awarding any winnings to the User.</li>
        </ul>
        <p>
          By accepting the Terms and Conditions of DREAMSPORT, Users agree to provide accurate, current and complete information during the registration process and at other times as required by DREAMSPORT. Users also agree to keep their registration information up-to-date.
        </p>
        <p>
          Each User is allowed to register and operate only one account with DREAMSPORT, whether on the website or the app.
        </p>
        <p>
          Users consent to receive all communications from DREAMSPORT by marking DREAMSPORT emails as “safe senders.” If a user does not receive DREAMSPORT emails due to them being sent to the spam or junk folder, DREAMSPORT will not be held responsible.
        </p>
        <p>
          Any password issued by DREAMSPORT to a User is confidential and must not be shared with anyone else. Users are solely responsible for maintaining the confidentiality of their accounts and passwords and agree to immediately notify DREAMSPORT of any unauthorized use of their passwords or accounts or any other security breach.
        </p>
        <p>
          Users are solely responsible for the security and confidentiality of any payment accounts linked to their DREAMSPORT account. In case of any misuse of the linked payment accounts, DREAMSPORT will not be liable and such misuse must be reported to DREAMSPORT immediately.
        </p>
        <p>
          Users agree to log out of their accounts after the completion of each session. In the event of any loss or damage resulting from the failure to do so, DREAMSPORT will not be held responsible.
        </p>
        <p>
          Users agree not to engage in or assist in the use of cheats, exploits, automation, software, bots, hacks, or any unauthorized third-party software designed to modify or interfere with DREAMSPORT features and/or experience.
        </p>
        <p>
          Users agree not to copy or modify the technology and software associated with DREAMSPORT and its features, nor to rent, loan, sell, assign, distribute, reverse engineer, grant a security interest in or otherwise transfer any rights to any of the associated technologies and software.
        </p>
        <p>
          Users agree not to modify or cause the modification of any files, technology or software associated with DREAMSPORT.
        </p>
        <p>
          Users agree not to disrupt or overburden the servers or computers supporting DREAMSPORT services or the enjoyment of DREAMSPORT features by other users or persons.
        </p>
        <p>
          Users agree not to access DREAMSPORT User accounts, servers, or networks associated with DREAMSPORT features by any means other than the user interface provided by DREAMSPORT. Users also agree not to engage in activities designed to circumvent or modify any security, technology, device or software associated with DREAMSPORT features.
        </p>
        <p>
          Users agree not to use the DREAMSPORT platform for any illegal or inappropriate activities, including, but not limited to:
        </p>
        <ul>
          <li>Any action or communication that is obscene, offensive, indecent, racial, communal, anti-national, objectionable, defamatory or abusive;</li>
          <li>Harassment, stalking, threatening or otherwise violating the legal rights of others;</li>
          <li>Transmitting files that contain viruses, corrupted files, or any other software or programs that may cause damage or negatively impact the operation of another person’s computer, www.dreamsport.shop, DREAMSPORT application or any software, hardware or telecommunications equipment;</li>
          <li>Advertising, offering or selling any goods or services for commercial purposes without the express written consent of DREAMSPORT;</li>
          <li>Transmitting content related to services, products, surveys, contests, pyramid schemes, spam, unsolicited advertising or promotional materials, or chain letters.</li>
        </ul>
        <p>
          The User shall not engage in or support any sort of attack on DREAMSPORT, including but not limited to the distribution of a virus, denial of service or other attempts to interrupt the services provided by DREAMSPORT or the use or enjoyment of other DREAMSPORT users.
        </p>
      </section>

      <section>
        <h2>Registration</h2>
        <p>
          To sign up for an account on DREAMSPORT, Users must provide their mobile number, which will receive a One-Time Password (OTP) for verification. Additionally, they can enter a referral code to receive a ₹25 Cash Bonus.
        </p>
        <p>
          Users can also sign-up using Truecaller if they have a Truecaller account and app installed on their phone.
        </p>
        <p>
          Once the User receives the OTP, they must enter it to complete the registration process and log in to their account. To participate in contests, Users must provide accurate information such as their date of birth and the pin code of their residence. The information provided for verification must match the information on their required documents.
        </p>
        <p>
          Before using any of the features provided by DREAMSPORT, participants must acknowledge that they have read and understood the Terms and Conditions and will comply with all the rules, regulations, and terms of use.
        </p>
        <p>
          Certain states in India have implemented limitations on fantasy sports and real money gaming platforms and are designated as restricted states.
        </p>
        <p>
          Please note that residents of Assam, Odisha, Telangana, Nagaland, Sikkim and Andhra Pradesh cannot participate in pay-to-play contests for fantasy sports. If a User accessing the services of DREAMSPORT is found to be a resident of any of these restricted states, he/she will be entirely liable for any legal or penal consequences. DREAMSPORT reserves the right to delete or deactivate their account and forfeit any remaining balance in their account.
        </p>
        <p>
          Furthermore, residents of Andhra Pradesh, Assam, Nagaland, Odisha, Sikkim and Telangana cannot use the Rummy game on the DREAMSPORT application. Finally, residents of these states (excluding Gujarat and Tamil Nadu) cannot use skill-based games on the DREAMSPORT application.
        </p>
        <table>
          <thead>
            <tr>
              <th>BANNED STATES</th>
              <th>FANTASY SPORTS</th>
              <th>RUMMY</th>
              <th>POKER</th>
              <th>SKILL BASED GAMES</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>Andhra Pradesh</td>
              <td>False</td>
              <td>False</td>
              <td>False</td>
              <td>False</td>
            </tr>
            <tr>
              <td>Assam</td>
              <td>False</td>
              <td>False</td>
              <td>False</td>
              <td>False</td>
            </tr>
            <tr>
              <td>Nagaland</td>
              <td>False</td>
              <td>False</td>
              <td>False</td>
              <td>False</td>
            </tr>
            <tr>
              <td>Odisha</td>
              <td>False</td>
              <td>False</td>
              <td>False</td>
              <td>False</td>
            </tr>
            <tr>
              <td>Sikkim</td>
              <td>False</td>
              <td>False</td>
              <td>False</td>
              <td>False</td>
            </tr>
            <tr>
              <td>Telangana</td>
              <td>False</td>
              <td>False</td>
              <td>False</td>
              <td>False</td>
            </tr>
            <tr>
              <td>Gujarat</td>
              <td>True</td>
              <td>True</td>
              <td>False</td>
              <td>True</td>
            </tr>
            <tr>
              <td>Tamil Nadu</td>
              <td>True</td>
              <td>True</td>
              <td>True</td>
              <td>True</td>
            </tr>
          </tbody>
        </table>
      </section>

      <section>
        <h2>Contests, Participation, and Prizes</h2>
        <p>
          The DREAMSPORT platform conducts various contests as part of the features offered by DREAMSPORT. These contests include fantasy cricket, football, kabaddi, volleyball, basketball, handball, hockey, baseball, rugby and US football. Participants in the contests create fantasy teams consisting of on-field players from the relevant match, series or tournament. Points are awarded based on the performance of these players and the user with the highest aggregate of points is declared winner of the contest. DREAMSPORT may declare more than one winner and distribute winnings accordingly in increasing order of their teams’ scores. The contests comply with the “Fantasy Rules” and other terms, conditions and regulations mentioned in the “How To Play” section.
        </p>
        <p>
          Users may participate in paid versions of the contests by paying a pre-defined entry fee, as stated on the relevant contest page. An individual is authorized to create multiple teams for participating in contests unless otherwise specified. In the case of multiple-entry contests, users may submit more than one team but are not allowed to edit their teams after the match deadline is closed. DREAMSPORT may limit the number of multiple teams allowed in a contest or the number of teams a single user account can create.
        </p>
        <p>
        DREAMSPORT is authorized to charge a predefined entry fee for accessing the features. However, residents of restricted states are not allowed to participate in paid versions of the contests.
        </p>
        <p>
        DREAMSPORT offers three variations in contests:
        </p>
        <ul>
          <li>
            <strong>Guaranteed Contests:</strong> As the name suggests, guaranteed contests offer guaranteed winnings and will not get cancelled, even if they do not meet the participant requirements/spots.
          </li>
          <li>
            <strong>Flexible Contests:</strong> In flexible contests, there should be at least 3 users and a maximum of 100 users in the contest. If there are two users in the flexible contest, the respective contest will be converted into head-to-head. The flexible contests will get cancelled if the contest receives less than 50% participation.
            <p>For instance:</p>
            <p>If a flexible contest has a total of 20 spots and 8 users join the contest, this contest will be cancelled. For this flexible contest to carry on, a minimum of 10 users are required to join.</p>
          </li>
          <li>
            <strong>Guaranteed + Flexible Contests:</strong> Users will also find flexible + guaranteed contests. In these contests, league price and winning is varied depending on the number of users joining the contest. This contest will not get cancelled, irrespective of number of users joining the contest.
            <p>Please note that the league price and winning distribution of flexible contests and Guaranteed + Flexible Contests will change once the match is live.</p>
          </li>
        </ul>
        <p>
        DREAMSPORT holds the right to abandon a contest, adjust its deadline, or change the deadline in unavoidable circumstances beyond its control. The platform can adjust the deadline by 10 minutes or 3 overs (whichever is less) before the official match start time for cricket and by a maximum of 10 minutes for other sports. If DREAMSPORT is unable to cross-check the official match start time, it may adjust its deadline such that a maximum of 3 overs are bowled in the adjusted time. In the case of the official match start time being after DREAMSPORT deadline, the platform may abandon, cancel or delay the start of the contest by extending the deadline in certain unavoidable circumstances, such as weather conditions, technical glitches, non-appearance of teams, natural disasters, etc.
        </p>
      </section>

      <section>
        <h2>Play Formats</h2>
        <p>
          The game format offered on DREAMSPORT allows the Users to create their teams even after the playing team for a respective match has been announced. The Users are allowed to create or edit their teams till the last moment, i.e., right before the beginning of the real match.
        </p>
        <p>
          The deadline for creating or editing teams is determined by the official start of the match, which may either be extended or shortened based on the sport being played. It is recommended that users save their teams frequently.
        </p>
        <p>
          The playing team information for live matches is sourced either from official sources or our experts but does not guarantee 100% accuracy. This information may be updated at any time.
        </p>
        <p>
          A green dot will be displayed next to the player's name on the Create Team page once the playing team information has been received from official sources.
        </p>
        <p>
          In the event of errors or inaccuracies in the playing team information due to the official data provider’s shortcomings, no contest entry amount will be refunded. Users are advised to cross-check playing team information on other official platforms.
        </p>
        <p>
          It is possible that playing team information may not be available right before the start of the live match, but this occurs infrequently. Users are advised to be aware of this possibility.
        </p>
      </section>

      <section>
        <h2>Contest Formats</h2>
        <p>
        DREAMSPORT conducts contests as part of its features, offering both public and private contest options for Users to participate. The following Terms and Conditions apply to both public and private contests (but are not limited to):
        </p>
        <h3>Public Contest:</h3>
        <ul>
          <li>DREAMSPORT may offer a pre-defined number of participants for the public contest format of the contest.</li>
          <li>The public contest format of the contest may be conducted as a paid contest, and the winner may be announced at the end of the contest.</li>
          <li>The minimum number of participants required to make the contest operational may be pre-defined by DREAMSPORT. If the required number of participants is reached, the contest will start as scheduled. If not, the contest will be cancelled and the contest entry fee will be refunded to participants without any deductions or charges.</li>
          <li>DREAMSPORT is solely authorized to change or alter the total winning amount and the number of winners in any flexible public contest(s) on the app. For instance, the Infinity Contest on DREAMSPORT is a flexible fantasy contest where the total winning amount and the number of winners are variable and can be changed at any given time, following the total number of participants in the respective contest(s). All the decisions or changes are made under the sole discretion of DREAMSPORT Fantasy Sports Pvt. Ltd.</li>
        </ul>
        <h3>“Teams War” Contest:</h3>
        <p>
          Points will be awarded to teams based on the performance of their individual players. The individual or team with the highest total points at the end of the match will be declared the winner.
        </p>
        <p>
          The total points you have in the contest will be calculated by adding up the points from all of your teams. If you have multiple teams, the points from each of them will be combined to give your overall total points.
        </p>
        <p>
          In the event of a tie, the prize money will be split equally between all participants with the highest points.
        </p>
        <h3>Private Contest:</h3>
        <p>
          Users can create their own contests on DREAMSPORT, invite others to join and set up private leagues with their friends. Private contests allow participants to join contests created by other users, which may have a different set of rules and entry fees than those offered in public contests.
        </p>
        <ul>
          <li>Private contests are created by users and can only be accessed by invitation. Users can invite friends, colleagues and other contacts to join their contests.</li>
          <li>The user who creates a private contest is referred to as the ‘Creator’. The creator can set the number of participants, entry fees, prizes and other contest parameters.</li>
          <li>Once a private contest is created, it is the responsibility of the creator to manage and maintain the contest, including resolving any issues or disputes that arise.</li>
          <li>Users who join private contests agree to comply with the rules and regulations set by the creator. Participants must not engage in any fraudulent or unfair practices to gain an advantage.</li>
          <li>Private contests are subject to all applicable laws and regulations. Users are responsible for ensuring that their contests comply with any legal requirements in their jurisdiction.</li>
          <li>DREAMSPORT reserves the right to cancel or terminate any private contest if it violates the terms and conditions or is found to be involved in illegal activities.</li>
        </ul>
        <p>
          The maximum number of participants required for a contest to start may vary depending on the type of contest. If the required number of participants is not met, the contest will be cancelled and the entry fee will be refunded to participants without any deductions or charges.
        </p>
      </section>

      <section>
        <h2>Contestant Selection and Evaluation Criteria</h2>
        <p>
          Participants must select their teams in accordance with the rules and criteria specified for each contest. Teams will be evaluated based on the performance of the players in the actual match or event. DREAMSPORT reserves the right to modify the criteria for evaluation of teams and award points at its sole discretion.
        </p>
        <p>
          The decision of DREAMSPORT regarding the evaluation of teams and the distribution of prizes will be final and binding on all participants. DREAMSPORT reserves the right to disqualify any participant or team if it is found to have violated the terms and conditions or engaged in any unfair practices.
        </p>
        <p>
          Participants must adhere to the deadlines and timelines specified for each contest. Any changes or modifications to the team after the deadline will not be accepted.
        </p>
        <p>
          DREAMSPORT is not responsible for any errors or discrepancies in the data provided by third-party sources or official match organizers. Participants are advised to cross-check the data and information provided on the platform before making their selections.
        </p>
      </section>

      <section>
        <h2>Prize Distribution and Withdrawals</h2>
        <p>
          The prize distribution for each contest will be as per the pre-defined structure specified on the contest page. The distribution of prizes is subject to the completion of the match and the final verification of the results.
        </p>
        <p>
          Participants must comply with the withdrawal policies and procedures specified by DREAMSPORT to withdraw their winnings. The withdrawal process may include verification of the participant’s identity, bank account details, and other relevant information.
        </p>
        <p>
          DREAMSPORT reserves the right to withhold or cancel any withdrawal request if it suspects any fraudulent activity or violation of the terms and conditions by the participant.
        </p>
        <p>
          The withdrawal process may take up to 5-7 working days, depending on the verification and processing time required by the payment providers. Participants are advised to provide accurate and up-to-date information to avoid any delays or issues in the withdrawal process.
        </p>
        <p>
          DREAMSPORT is not responsible for any charges or fees imposed by the payment providers or banks for the withdrawal of winnings. Participants must bear any such charges or fees as per the policies of the respective payment providers or banks.
        </p>
      </section>

      <section>
        <h2>Dispute Resolution</h2>
        <p>
          In case of any disputes or disagreements regarding the terms and conditions, the evaluation of teams, or the distribution of prizes, the decision of DREAMSPORT will be final and binding on all participants.
        </p>
        <p>
          Participants are advised to contact DREAMSPORT customer support for any queries or issues related to the contests or features. DREAMSPORT will make reasonable efforts to resolve any disputes or issues in a timely and fair manner.
        </p>
        <p>
          If the dispute cannot be resolved through mutual agreement, it will be referred to arbitration as per the provisions of the Indian Arbitration and Conciliation Act, 1996. The arbitration proceedings will be conducted in Gurgaon, Haryana, and the decision of the arbitrator will be final and binding on both parties.
        </p>
        <p>
          Participants agree to indemnify and hold harmless DREAMSPORT, its affiliates, partners, licensors, and associates from any claims, damages, losses, or expenses arising from their participation in the contests or use of the features provided by DREAMSPORT.
        </p>
      </section>

      <section>
        <h2>Governing Law and Jurisdiction</h2>
        <p>
          These terms and conditions will be governed by and construed in accordance with the laws of India. Any legal proceedings arising out of or related to these terms and conditions or the contests and features provided by DREAMSPORT will be subject to the exclusive jurisdiction of the courts in Gurgaon, Haryana.
        </p>
        <p>
          Participants agree to comply with all applicable laws and regulations in their jurisdiction while using the services and features provided by DREAMSPORT. It is the responsibility of the participants to ensure that their use of the platform and participation in the contests does not violate any legal or regulatory requirements.
        </p>
        <p>
          If any provision of these terms and conditions is found to be invalid or unenforceable by a court of competent jurisdiction, the remaining provisions will continue to be in full force and effect. The invalid or unenforceable provision will be replaced by a valid and enforceable provision that most closely matches the intent of the original provision.
        </p>
      </section>

      <section>
        <h2>Changes to Terms and Conditions</h2>
        <p>
          DREAMSPORT reserves the right to modify or update these terms and conditions at any time without prior notice. Participants are advised to review the terms and conditions periodically to stay informed about any changes or updates.
        </p>
        <p>
          Continued use of the DREAMSPORT platform and participation in the contests after any modifications or updates to the terms and conditions will constitute acceptance of the revised terms and conditions.
        </p>
      </section>

      <section>
        <h2>Contact Information</h2>
        <p>
          For any queries or issues related to the terms and conditions, participants can contact DREAMSPORT customer support at support@dreamsport.shop or info@dreamsport.shop.
        </p>
        <p>
          Participants can also reach out to DREAMSPORT at the following address:
        </p>
        <address>
          DREAMSPORT Fantasy Sports Private Limited<br />
          Accelerator Coworking Space<br />
          Ground Floor, MGF Metropolis Mall<br />
          Mehrauli-Gurgaon Rd<br />
          Gurugram, Haryana 122002
        </address>
      </section>
    </div>
  );
};

export default TermsAndConditions;
